name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docusaurus-test  # Set this to the path of your Docusaurus project

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18'  # Use the node version compatible with your project

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Deploy
      run: |
        git config --global user.name 'Evan Brothers'
        git config --global user.email 'ekbrothers@gmail.com'
        echo "machine github.com login ${{ github.actor }} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
        npm run deploy
      env:
        USE_SSH: true
        GIT_USER: ${{ github.actor }}
        DEPLOYMENT_BRANCH: gh-pages
