name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docusaurus-test  # Set this to the path of your Docusaurus project

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18'  # Use the node version compatible with your project

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Deploy
      run: |
        git config --global user.name 'Evan Brothers'
        git config --global user.email 'ekbrothers@gmail.com'
        # No need to set up SSH or modify ~/.netrc for HTTPS
        npm run deploy
      env:
        # Use the automatically created GITHUB_TOKEN secret
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOYMENT_BRANCH: main
